#include "scanmatch.h"
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static size_t cp_len(const unsigned char *s){if(!s||!*s)return 0;if(*s<0x80)return 1;if((*s&0xE0)==0xC0)return 2;if((*s&0xF0)==0xE0)return 3;if((*s&0xF8)==0xF0)return 4;return 1;}
static unsigned cp_decode(const unsigned char*s,size_t n){if(n==1)return s[0];if(n==2)return((unsigned)(s[0]&31)<<6)|(s[1]&63);if(n==3)return((unsigned)(s[0]&15)<<12)|((unsigned)(s[1]&63)<<6)|(s[2]&63);return((unsigned)(s[0]&7)<<18)|((unsigned)(s[1]&63)<<12)|((unsigned)(s[2]&63)<<6)|(s[3]&63);}
static size_t cp_array(const char*s,unsigned *a,size_t cap){size_t n=0;if(!s)return 0;for(size_t i=0;s[i]&&n<cap;){size_t k=cp_len((const unsigned char*)s+i);a[n++]=cp_decode((const unsigned char*)s+i,k);i+=k;}return n;}

double sm_utf8_similarity(const char*a,const char*b){if(!a||!b)return 0;if(!*a&&!*b)return 1;if(!*a||!*b)return 0;unsigned A[SM_MAX_TEXT],B[SM_MAX_TEXT];size_t na=cp_array(a,A,SM_MAX_TEXT),nb=cp_array(b,B,SM_MAX_TEXT);size_t *prev=malloc((nb+1)*sizeof(size_t)),*cur=malloc((nb+1)*sizeof(size_t));if(!prev||!cur){free(prev);free(cur);return 0;}for(size_t j=0;j<=nb;j++)prev[j]=j;for(size_t i=1;i<=na;i++){cur[0]=i;for(size_t j=1;j<=nb;j++){size_t d=prev[j]+1,u=cur[j-1]+1,l=prev[j-1]+(A[i-1]!=B[j-1]);cur[j]=d<u?(d<l?d:l):(u<l?u:l);}size_t*t=prev;prev=cur;cur=t;}size_t d=prev[nb],m=na>nb?na:nb;free(prev);free(cur);return m?1.0-(double)d/(double)m:1.0;}

double sm_token_overlap(const char*a,const char*b){char A[SM_MAX_TEXT],B[SM_MAX_TEXT];sm_normalize_text(a,A,sizeof(A));sm_normalize_text(b,B,sizeof(B));int total=0,common=0;char*sa=NULL;for(char*x=strtok_r(A," ",&sa);x;x=strtok_r(NULL," ",&sa)){total++;char BB[SM_MAX_TEXT];snprintf(BB,sizeof(BB),"%s",B);char*sb=NULL;for(char*y=strtok_r(BB," ",&sb);y;y=strtok_r(NULL," ",&sb))if(strcmp(x,y)==0){common++;break;}}return total?(double)common/total:0;}
double sm_hybrid_similarity(const char*a,const char*b){char A[SM_MAX_TEXT],B[SM_MAX_TEXT];sm_normalize_text(a,A,sizeof(A));sm_normalize_text(b,B,sizeof(B));double t=sm_utf8_similarity(A,B),o=sm_token_overlap(A,B);return strcmp(A,B)==0?1.0:.65*t+.35*o;}
const char*sm_confidence_band(double s){return s>=.90?"HIGH":s>=.70?"MEDIUM":"LOW";}
double sm_cosine_similarity(const float*a,const float*b,size_t n){double d=0,x=0,y=0;if(!a||!b)return 0;for(size_t i=0;i<n;i++){d+=a[i]*b[i];x+=a[i]*a[i];y+=b[i]*b[i];}return x>0&&y>0?d/(sqrt(x)*sqrt(y)):0;}
static void trim(char*s){size_t n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]=0;size_t i=0;while(s[i]&&isspace((unsigned char)s[i]))i++;if(i)memmove(s,s+i,strlen(s+i)+1);}
static int split_csv(char*line,char**fields,int max){int n=0,in=0;fields[n++]=line;for(char*p=line;*p;p++){if(*p=='"'){if(in&&p[1]=='"')p++;else in=!in;}else if(*p==','&&!in){*p=0;if(n<max)fields[n++]=p+1;}}return n;}
static void unquote(char*s){trim(s);size_t n=strlen(s);if(n>=2&&s[0]=='"'&&s[n-1]=='"'){s[n-1]=0;memmove(s,s+1,n-1);}}
static void add_list(char dst[][SM_MAX_ALIAS],size_t*cnt,size_t max,const char*s){char tmp[4096];snprintf(tmp,sizeof(tmp),"%s",s?s:"");char*save=NULL;for(char*x=strtok_r(tmp,"|;\r\n",&save);x&&*cnt<max;x=strtok_r(NULL,"|;\r\n",&save)){trim(x);if(*x)snprintf(dst[(*cnt)++],SM_MAX_ALIAS,"%s",x);}}
static void add_unit(SM_Product*p,const char*s){if(!s||!p||p->unit_count>=16)return;snprintf(p->units[p->unit_count++],32,"%s",s);}
int sm_load_catalog_csv(const char*path,SM_Product*p,size_t max,size_t*out){if(!path||!p||!out)return-1;FILE*f=fopen(path,"rb");if(!f)return-2;char line[16384];size_t n=0;int first=1;while(n<max&&fgets(line,sizeof(line),f)){if(first){first=0;if(strstr(line,"product_id")||strstr(line,"sku"))continue;}if(line[0]=='#'||line[0]=='\n'||line[0]=='\r')continue;char*F[12]={0};int nf=split_csv(line,F,12);if(nf<4)continue;SM_Product*q=&p[n];memset(q,0,sizeof(*q));for(int i=0;i<nf;i++)unquote(F[i]);snprintf(q->sku,sizeof(q->sku),"%s",F[0]);snprintf(q->canonical_name,sizeof(q->canonical_name),"%s",F[1]);if(nf>=10){snprintf(q->brand,sizeof(q->brand),"%s",F[2]);snprintf(q->category,sizeof(q->category),"%s",F[3]);add_list(q->aliases,&q->alias_count,SM_MAX_ALIASES,F[4]);add_list(q->aliases,&q->alias_count,SM_MAX_ALIASES,F[5]);add_list(q->aliases,&q->alias_count,SM_MAX_ALIASES,F[6]);add_list(q->ocr_errors,&q->ocr_error_count,SM_MAX_ERRORS,F[7]);char tmp[2048];snprintf(tmp,sizeof(tmp),"%s|%s",F[8],F[9]);char*sv=NULL;for(char*x=strtok_r(tmp,"|;\r\n",&sv);x&&q->unit_count<16;x=strtok_r(NULL,"|;\r\n",&sv))add_unit(q,x);}else{snprintf(q->category,sizeof(q->category),"%s",F[2]);add_list(q->aliases,&q->alias_count,SM_MAX_ALIASES,F[3]);}n++;}fclose(f);*out=n;return 0;}
static double best_alias(const char*text,const SM_Product*p,double*exact,double*brand){double best=sm_hybrid_similarity(text,p->canonical_name);*exact=best>=.999?1.0:0;for(size_t j=0;j<p->alias_count;j++){double s=sm_hybrid_similarity(text,p->aliases[j]);if(s>best)best=s;if(s>=.999)*exact=1.0;}for(size_t j=0;j<p->ocr_error_count;j++){double s=sm_hybrid_similarity(text,p->ocr_errors[j]);if(s>best)best=s;}*brand=p->brand[0]?sm_hybrid_similarity(text,p->brand):0;return best;}
int sm_match_product_hybrid(const SM_ListItem*i,const SM_Product*p,size_t count,SM_ProductMatch*out,size_t max,SM_EmbeddingFn ef,void*ud){if(!i||!p||!out||!max)return-1;if(count>SM_MAX_PRODUCTS)count=SM_MAX_PRODUCTS;SM_ProductMatch*tmp=calloc(count,sizeof(*tmp));if(!tmp)return-2;for(size_t k=0;k<count;k++){double exact=0,brand=0,best=best_alias(i->product_text,&p[k],&exact,&brand);double tok=sm_token_overlap(i->product_text,p[k].canonical_name);for(size_t j=0;j<p[k].alias_count;j++)tok=fmax(tok,sm_token_overlap(i->product_text,p[k].aliases[j]));double unit_score=0;if(i->unit[0]&&p[k].unit_count)for(size_t j=0;j<p[k].unit_count;j++)if(sm_hybrid_similarity(i->unit,p[k].units[j])>.99){unit_score=1;break;}double emb=-1;if(ef){float a[1024],b[1024];if(ef(i->product_text,a,1024,ud)==0&&ef(p[k].canonical_name,b,1024,ud)==0)emb=(sm_cosine_similarity(a,b,1024)+1)/2;}double catalog=.45+.35*fmax(exact,fmax(best,tok))+.20*unit_score;double ocr=i->ocr_confidence>0?i->ocr_confidence:.70;double score=.40*best+.20*tok+.18*exact+.07*brand+.10*ocr+.05*unit_score;if(exact>0.99)score+=.08;else if(best>.88)score+=.03;if(emb>=0)score=.85*score+.15*emb;if(score>1)score=1;snprintf(tmp[k].sku,sizeof(tmp[k].sku),"%s",p[k].sku);snprintf(tmp[k].canonical_name,sizeof(tmp[k].canonical_name),"%s",p[k].canonical_name);tmp[k].score=score;tmp[k].text_score=best;tmp[k].token_score=tok;tmp[k].embedding_score=emb;tmp[k].exact_alias_score=exact;tmp[k].brand_score=brand;tmp[k].catalog_evidence=catalog;snprintf(tmp[k].confidence_band,sizeof(tmp[k].confidence_band),"%s",sm_confidence_band(score));}for(size_t a=0;a<count;a++)for(size_t b=a+1;b<count;b++)if(tmp[b].score>tmp[a].score){SM_ProductMatch t=tmp[a];tmp[a]=tmp[b];tmp[b]=t;}size_t n=count<max?count:max;for(size_t k=0;k<n;k++)out[k]=tmp[k];free(tmp);return(int)n;}
